spring.application.name=student-forum
spring.datasource.url=${DB_FORUM}
spring.datasource.username=${DB_FORUM_USER}
spring.datasource.password=${DB_FORUM_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true